WRITE_ERROR_MSG = "Ошибка записи последнего запроса в файл"
HISTORY_ERROR_MSG = "Ошибка считывания истории запросов"
FILE_NOT_FOUND_MSG = "Файл с историей не обнаружен"
UNKNOWN_ERROR = "Неизвестная ошибка"
UNKNOWN_COMMAND_MSG = "Неизвестная функция"
NOT_ENOUGHT_ARGS_MSG = "Недостаточно аргументов"
UNKNOWN = "unknown"
BAD_ARGS = "Неправильно задан аргумент"
